---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [5.2.1-r6, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [5.2.1-r6, latest]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: b2cafbacc284d4ec33aaa3841d0ebe65cb2668338a940c910c328e317286dd21

...
