---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r4, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r4, latest]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 4791d35667ff53003dc11f05c624092379156c0d48408c16d50377568e7a423f

...
