---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r1, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r1, latest]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: e79f0939b2e6a1a0d9bd9437eba31ba96b3de60d258383f3323fe331b179ff97

...
