---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r5, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/varnish
    tags: [6.3.1-r5, latest]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 708abea9dd6c094f313b499db116846220364831160cb063e3bcd6446acaf545

...
